# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsomeProject', '0004_auto_20170203_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
