# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 16:16
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsomeProject', '0004_auto_20170203_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=cloudinary.models.CloudinaryField(default='1', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='1', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
