# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awsomeProject', '0004_gamehighscores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameHighScores',
            new_name='Scores',
        ),
    ]
