# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awsomeProject', '0005_auto_20170206_1356'),
        ('awsomeProject', '0005_auto_20170206_1816'),
    ]

    operations = [
    ]
