# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awsomeProject', '0005_auto_20170204_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameimage',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profileimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profileimage',
            name='user',
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='awsomeProject.Photo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='awsomeProject.Photo'),
        ),
        migrations.DeleteModel(
            name='GameImage',
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
