# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awsomeProject', '0006_merge_20170207_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awsomeProject.Photo'),
        ),
    ]
