# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 14:14
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awsomeProject', '0007_auto_20170206_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
        ),
    ]
