# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awsomeProject', '0006_merge_20170207_1643'),
        ('awsomeProject', '0009_auto_20170207_1555'),
    ]

    operations = [
    ]
