# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awsomeProject', '0011_auto_20170214_1103'),
        ('awsomeProject', '0011_auto_20170213_1836'),
    ]

    operations = [
    ]
