# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsomeProject', '0012_merge_20170214_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
