# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awsomeProject', '0012_auto_20170208_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
