# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsomeProject', '0014_auto_20170213_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Advanture', 'Adventure'), ('Sports', 'Sports'), ('Strategy', 'Strategy')], default='Action', max_length=20),
        ),
    ]
