# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsomeProject', '0015_game_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='', max_length=400),
        ),
    ]
