# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsomeProject', '0016_auto_20170213_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
